modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="the_box"
version="2.3.1"
displayName="The Box"
displayURL="https://github.com/CallMeiota/The-Box"
logoFile="logo.png"
credits="Go to CallMeiota for making a weird but functional box."
authors="CallMeiota"
description="Adds a new and improved item to the game."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.the_box]]
modId="neoforge"
type="required"
versionRange="[21.1.65,)"
ordering="AFTER"
side="BOTH"

[[dependencies.the_box]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"

[[dependencies.the_box]]
modId="geckolib"
type="required"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.the_box]]
modId="geckolib"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration